export interface SpotlightAlumnus {
  id: string;
  name: string;
  period: string;
  profession: string;
  workStation: string;
  imageUrl: string;
}

// Built from the image filenames in public/spotlight2/
// Filename convention: [period]_Name_Profession_WorkStation.ext
const spotlightData: SpotlightAlumnus[] = [
  {
    id: '1',
    name: 'Twebaze Paul',
    period: '1997-1999',
    profession: 'Research Fellow',
    workStation: 'ACODE',
    imageUrl: '/spotlight2/[1997-1999]_Twebaze Paul-Research Fellow _ ACODE.png',
  },
  {
    id: '2',
    name: 'Dr. Atukwatse Judith',
    period: '1998-2000',
    profession: 'DDAA',
    workStation: 'Kampala International University',
    imageUrl: '/spotlight2/[1998-2000]_Dr.Atukwatse Judith_DDAA_Kampala International University.png',
  },
  {
    id: '3',
    name: 'Kwatampoora Kansiime Vicent',
    period: '1999-2001',
    profession: 'US',
    workStation: 'Mbarara University',
    imageUrl: '/spotlight2/[1999-2001]_Kwatampoora Kansiime Vicent _US_Mbarara University.png',
  },
  {
    id: '4',
    name: 'Mugumya Winston',
    period: '2000-2001',
    profession: 'Mechanical Engineer',
    workStation: 'MoM&E',
    imageUrl: '/spotlight2/[2000-2001]-Mugumya Winston-Mechanical Engineer -MoM&E.png',
  },
  {
    id: '5',
    name: 'Justus Rukundo',
    period: '2003 - 2008',
    profession: 'Electrical Engineer',
    workStation: 'ATC',
    imageUrl: '/spotlight2/[2003 - 2008]_Justus Rukundo_Electrical Engineer_ATC.jpeg',
  },
  {
    id: '6',
    name: 'Atuhaire Phionah',
    period: '2004 - 2005',
    profession: 'Medical Laboratory Technologist',
    workStation: 'Uganda Virus Research Institute Entebbe',
    imageUrl: '/spotlight2/[2004 - 2005]_ATUHAIRE PHIONAH_Medical Laboratory technologist_Uganda Virus Research institute Entebbe.png',
  },
  {
    id: '7',
    name: 'Dr. Ndyabakira Alex',
    period: '2004-2005',
    profession: 'Medical Doctor',
    workStation: 'KCCA',
    imageUrl: '/spotlight2/[2004-2005]-DR. Ndyabakira Alex - Medical Doctor - KCCA.png',
  },
  {
    id: '8',
    name: 'Arinaitwe Robert',
    period: '2004-2005',
    profession: 'Lawyer',
    workStation: 'State Attorney, Office of Director of Public Prosecutions',
    imageUrl: '/spotlight2/[2004-2005]_Arinaitwe Robert_Lawyer_State Attorney, Office of Director of Public Prosecutions.png',
  },
  {
    id: '9',
    name: 'Counsel Pearl Atukunda',
    period: '2004-2005',
    profession: 'Lawyer-UN',
    workStation: 'United Nations',
    imageUrl: '/spotlight2/[2004-2005]_Counsel Pearl Atukunda_Lawyer-UN_United Nations.png',
  },
  {
    id: '10',
    name: 'Eng. Moses Agaba (CEng)',
    period: '2004-2005',
    profession: 'Engineer - Head of Engineering & Production',
    workStation: 'Engineering Development and Innovation Centre (EDiC), Namanve',
    imageUrl: '/spotlight2/[2004-2005]_Eng. Moses Agaba (CEng)_Engineer - Head of Engineering & Production_Engineering Development and Innovation Centre (EDiC), Kampala Industrial & Business Park - Namanve.JPG',
  },
  {
    id: '11',
    name: 'Kansiime Ibrahim',
    period: '2004-2005',
    profession: 'Accountant',
    workStation: 'URA',
    imageUrl: '/spotlight2/[2004-2005]_Kansiime Ibrahim_Accountant_URA.png',
  },
  {
    id: '12',
    name: 'Birungi Sandra',
    period: '2004-2007, 2008',
    profession: 'Teacher [AI Evaluator]',
    workStation: 'Sama',
    imageUrl: '/spotlight2/[2004-2007, 2008]_Birungi Sandra_Teacher [AI Evaluator]_Sama.png',
  },
  {
    id: '13',
    name: 'Hon. Kyinyamatama Juliet',
    period: '2004-2007',
    profession: 'W-MP',
    workStation: 'Rakai District',
    imageUrl: '/spotlight2/[2004-2007]_Hon.Kyinyamatama Juliet_W-MP_Rakai District.png',
  },
  {
    id: '14',
    name: 'Davis Tukamushaba',
    period: '2006-2007',
    profession: 'Mechanical Engineer',
    workStation: 'Ministry of Works & Transport',
    imageUrl: '/spotlight2/[2006-2007]_Davis Tukamushaba_Mechanical Engineer_Ministry of Works & Transport.png',
  },
  {
    id: '15',
    name: 'Heather Lambert',
    period: '2006-2007',
    profession: 'Financial Advisor-Administrator',
    workStation: 'Old Mutual Insurance',
    imageUrl: '/spotlight2/[2006-2007]_Heather Lambert_Financial Advisor-Administrator_Old mutual insurance.png',
  },
  {
    id: '16',
    name: 'Luka Layman',
    period: '2006-2007',
    profession: 'Branch Manager - African Trade Winds Ltd',
    workStation: 'Bundibugyo',
    imageUrl: '/spotlight2/[2006-2007]_Luka Layman_Branch Manager- African Trade Winds Ltd_Bundibugyo.png',
  },
  {
    id: '17',
    name: 'Ndyamwesiga Stephen',
    period: '2006-2007',
    profession: 'Engineer',
    workStation: 'Kampala',
    imageUrl: '/spotlight2/[2006-2007]_Ndyamwesiga stephen_Engineer_Kampala.png',
  },
  {
    id: '18',
    name: 'Nuwahumuza Mark',
    period: '2006-2007',
    profession: 'Consultant Sales Engineer',
    workStation: 'Epiroc Eastern Africa Limited',
    imageUrl: '/spotlight2/[2006-2007]_Nuwahumuza Mark_Consultant Sales Engineer_Epiroc Eastern Africa Limited.png',
  },
  {
    id: '19',
    name: 'Taremwa Elias',
    period: '2006-2007',
    profession: 'Engineer + Business Man',
    workStation: 'Uplink Builders Limited',
    imageUrl: '/spotlight2/[2006-2007]_Taremwa Elias_Engineer+Business Man_Uplink Builders Limited.png',
  },
  {
    id: '20',
    name: 'Barbra Atuhereza',
    period: '2007-2008',
    profession: 'Environmentalist',
    workStation: 'Geotropic Consults Ltd',
    imageUrl: '/spotlight2/[2007-2008]_Barbra Atuhereza_Geotropic Consults Ltd_Eviromentalist.png',
  },
  {
    id: '21',
    name: 'Kananura Keneth',
    period: '2007-2008',
    profession: 'Medical Doctor',
    workStation: 'Mbarara Regional Referral Hospital',
    imageUrl: '/spotlight2/[2007-2008]_Kananura Keneth_Medical doctor_Mbarara Regional Referral Hospital.png',
  },
  {
    id: '22',
    name: 'Brian Mutungi',
    period: '2008-2009',
    profession: 'Clinical (Imaging) Applications Specialist',
    workStation: 'Siemens Healthineers-Uganda',
    imageUrl: '/spotlight2/[2008-2009]_Brian Mutungi_Clinical(Imaging) Applications Specialist_Siemens Healthineers-Uganda.png',
  },
  {
    id: '23',
    name: 'Ezra Mugume',
    period: '2010 - 2011',
    profession: 'Business Consultant',
    workStation: 'Airtel Uganda Ltd',
    imageUrl: '/spotlight2/[2010 - 2011]_Ezra Mugume_Business Consultant_Airtel Uganda Ltd.png',
  },
  {
    id: '24',
    name: 'Kamusiime Anatori',
    period: '2013-2016',
    profession: 'Lawyer',
    workStation: 'D. Kagarura Advocates and Solicitors, Kampala Road',
    imageUrl: '/spotlight2/[2013-2016]_Kamusiime Anatori_Lawyer_D. Kagarura Advocates and Solicitors, Kampala road.png',
  },
  {
    id: '25',
    name: 'Michael Mukaira A',
    period: '1998-2000',
    profession: 'Architect + Urban Planner',
    workStation: 'Valley University',
    imageUrl: '/spotlight2/[1998-2000]_Michael Mukaira A_Architect+Urban Planner_Valley University.jpeg',
  },
  {
    id: '26',
    name: 'Kabezi Doreen',
    period: '1999-2000',
    profession: 'Headteacher',
    workStation: 'Valley College',
    imageUrl: '/spotlight2/[1999-2000]_Kabezi Doreen_Headteacher_Valley College.jpeg',
  },
];

export function getSpotlight(): SpotlightAlumnus[] {
  return spotlightData;
}
